### ISSUE TITLE
Hello world sample fails to build

### ISSUE THREAD

**Issue by jcoder58** [fable-compiler/samples-electron#14]
First, the build instructions in the README.md are wrong.  I followed those suggested in issue#10 and got

    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

     - configuration.output.path: The provided value "./app/js" is not an absolute path!

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
    npm ERR! node v7.2.0
    npm ERR! npm  v3.10.9 
    npm ERR! code ELIFECYCLE
    npm ERR! helloworld@1.0.0 build: `fable`
    npm ERR! Exit status 1
    npm ERR!   
    npm ERR! Failed at the helloworld@1.0.0 build script 'fable'.

I changed the output.path field to __dirname+"/app.js" which fixed the webpack error.

Once I made that change, it built ok and now runs

**Comment by alfonsogarciacaro** [comment]
Hi @jcoder58, thanks a lot for reporting and fixing the issue. I'm currently upgrading the fable-electron samples to Fable 1.0 (see https://github.com/fable-compiler/fable-electron/issues/13#issuecomment-296846896) so some changes are expected in the upcoming days :smile:

**Comment by jcoder58** [comment]
Thanks, @alfonsogarciacaro, looking forward to it.  The other examples need to be done as well as they all use older versions of fable.

An example using [electron-edge](https://github.com/kexplo/electron-edge) would also be a nice addition.   Building the gui using Fable with F#/.Net doing the heavy work would be a nice way to develop desktop apps.

**Comment by aolney** [comment]
FWIW I initially assumed I'd use electron-edge, but once I got into Fable I have never found it necessary.

**Comment by jmmk** [comment]
@jcoder58 Another option is to spin up a backend server as a child process of your app and treat is basically as a SPA with an HTTP API underneath. This is what I'm doing so that I can program with .NET libraries/ecosystem instead of Node.

I'm not using this library, but it's a good reference for how this looks: https://github.com/eliquious/electronify-server

Basically:

- Electron entry point spawns a child process calling your backend executable
- ping the server in a loop until you detect it's initialized
- Create BrowserWindow and make ajax requests from the frontend

**Comment by rahulpnath** [comment]
Faced the same issue, changed path to  **__dirname+"/app/js"** and got it working

**Comment by alfonsogarciacaro** [comment]
It took a while but we finally updated the sample to Fable 1.2 beta, could you give it a try? Please check README for instructions and note the name of the repo has changed to `samples-electron`.

> For now there's just one single example, we'll bring back the other (and new) samples later :)

**Comment by MangelMaxime** [comment]
I am closing this issue. Feel free to reopen if you still can't build the project.
