### ISSUE TITLE
Move to Fable 1.x

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/samples-electron#20]
@alfonsogarciacaro I just took a look at the repo and it's looks like some part are with Fable 1.0, others with Fable 0.7

Also, I don't really understand the samples directory or the idea behind the main project. I mean the `src` [folder](https://github.com/fable-compiler/fable-electron/tree/master/src) is empty. 

ping @majorgreys  who was trying to use this repo to learn Fable and Electron.

**Comment by alfonsogarciacaro** [comment]
Yeah, this repo needs some love. My plan is to move the bindings to fable-import and rename this as samples-electron, but I'm not sure if I'll be able to do it before FableConf 😕

**Comment by MangelMaxime** [comment]
No problem, I can give it a try.

I will create a basic PR and we will be able to start working from there.
