### ISSUE TITLE
Error on `dotnet restore` step

### ISSUE THREAD

**Issue by r4dian** [fable-compiler/samples-electron#25]
`C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Package dotnet-fable 1.2.0-beta-005 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package dotnet-fable 1.2.0-beta-005 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [C:\Users\Andrewse\Documents\GitHub\samples-electron\Fable.Samples.Electron.sln]
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [C:\Users\Andrewse\Documents\GitHub\samples-electron\Fable.Samples.Electron.sln]`

**Comment by aolney** [comment]
If you run `dotnet --version` I'm guessing it will say you are running 1.0. You need to upgrade to 2.0 AFAIK. If you have multiple `dotnet` installations on your system, you may need to change your path so that right one is accessed.

**Comment by r4dian** [comment]
Oh yes, that was it. Thanks.
