### ISSUE TITLE
Missing Fable.PowerPack dependency

### ISSUE THREAD

**Issue by rmunn** [fable-compiler/samples-electron#27]
Currently if you clone this repo and compile it, you'll get an F# compiler error saying that the namespace `PowerPack` is not defined. The solution is to add `nuget Fable.PowerPack` to `paket.dependencies` in the root folder, and add `Fable.PowerPack` to `src/Renderer/paket.references`.

**Comment by aolney** [comment]
BTW here's an [initial template for electron projects](https://github.com/aolney/fable-template-electron/tree/master/electron/Content)
