### ISSUE TITLE
Update paket.exe to the latest to fix Github error

### ISSUE THREAD

**Issue by SirUppyPancakes** [fable-compiler/samples-electron#30]
Downloaded the repo as a ZIP file, and extracted. Calls to `dotnet restore` were failing, because all calls to `packet.exe` were failing:
```
.\.paket\paket.exe
The request was aborted: Could not create SSL/TLS secure channel. (Github - cached (temporarily ignore updates))
```

Couldn't even get the version, the whole executable seems to have an issue. Right clicking in Windows and checking the file version revealed that it is `5.92.0-beta-003`. Following the steps for installing `paket` from their website (downloading the bootstrapper, renaming it, etc.) and installing the latest `5.148.0` seems to fix the issue.

Some manual searching found this:
https://github.com/fsprojects/Paket/issues/3065

It seems this issue has been fixed in the latest version.

It would be great if paket had a way to update itself (like npm), though it wouldn't have even solved this particular issue...

**Comment by alfonsogarciacaro** [comment]
Paket updates itself but the feature broke when Github deprecated SSL ;) Thanks a lot for the reminder, I'll update the binary :+1:
