### ISSUE TITLE
React.createElement with React.ClassicComponentClass

### ISSUE THREAD

**Issue by aolney** [fable-compiler/samples-electron#7]
I'm working on a new sample using D3 and React.

To do this, I'm creating a hybrid element like this:

```
let Chart : React.ClassicComponentClass<Datum array> = 
    React.createClass(  createObj [ ... ] :?> React.ComponentSpec<Datum array,obj> )
```

where `...` is a good size chunk of omitted code.

In my `view` function I'm trying to use:

```
React.Globals.createElement(``type``: ClassicComponentClass<'P>, props: 'P, [<ParamArray>] children: ReactNode[]): ClassicElement<'P> 
```

like this:

```
unbox( React.createElement( Chart,  unbox<Datum array>(model.Data), unbox(List.toArray []) ) )
```

but the compiler complains with

```
A unique overload for method 'createElement' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: 
member React.Globals.createElement : type:#React.ComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ReactElement<'P>, 
member React.Globals.createElement : type:#React.ComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ReactElement<'P>, 
member React.Globals.createElement : type:React.ClassicComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ClassicElement<'P>, 
member React.Globals.createElement : type:React.ClassicComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ClassicElement<'P> (L130,19-L130,104) 
```

I've tried doing [various type annotations suitable for overloaded methods](https://books.google.com/books?id=XKhPCwAAQBAJ&pg=PA51&lpg=PA51&dq=f%23+%22A+unique+overload+for+method%22+%22could+not+be+determined+based+on+type+information+prior+to+this+program+point.+A+type+annotation+may+be+needed.%22&source=bl&ots=GHWjkfBOf_&sig=rm0j8pJQ7F1WNg1VW_NsAnMchTk&hl=en&sa=X&ved=0ahUKEwiBscTdioHQAhVHOCYKHda2CXsQ6AEIOTAF#v=onepage&q=f%23%20%22A%20unique%20overload%20for%20method%22%20%22could%20not%20be%20determined%20based%20on%20type%20information%20prior%20to%20this%20program%20point.%20A%20type%20annotation%20may%20be%20needed.%22&f=false)
like this:

```
(React.createElement : React.ClassicComponentClass<obj> * obj * React.ReactNode [] -> React.ClassicElement<obj>) ( unbox(Chart),  unbox(model.Data), unbox(List.toArray []) ) :> React.ReactElement<obj>
```

This reduces but does not eliminate the error:

```
A unique overload for method 'createElement' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: 
member React.Globals.createElement : type:#React.ComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ReactElement<'P>, 
member React.Globals.createElement : type:React.ClassicComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ClassicElement<'P> (L133,13-L133,32) 
```

It seems like the problem is the # symbol, which indicates [flexible type](http://stackoverflow.com/questions/23088084/what-does-pound-sign-mean-in-type-signatures) -- I've never seen this before :smile: .

Because `ClassicComponentClass` inherits from `ComponentClass`, the compiler can't figure out how to resolve the overloaded method.

**Comment by alfonsogarciacaro** [comment]
The bindings in Fable.Import.React are automatically generated from Typescript declarations and are very confusing, I don't recommend using them directly. Can't you use the functions in Fable.Helpers.React? Is it not possible to inherit [React.Component](https://github.com/fable-compiler/Fable/blob/3f02941b5f3110887ddc11e040ae7684a612b69a/samples/browser/redux-webpack/components.fsx#L107-L138) or create a [stateless function](https://github.com/fable-compiler/Fable/blob/3f02941b5f3110887ddc11e040ae7684a612b69a/samples/browser/redux-webpack/components.fsx#L196-L208)?

**Comment by aolney** [comment]
Thanks :+1: Yes I think that is probably a better/cleaner way. 

It looks like maybe the overloading issue was not original to typescript and was [added in a PR](https://github.com/fable-compiler/Fable/pull/282)

FWIW I did manage to get this very close to working by doing my own import of react

`let ReactElement = importAll<obj> "react/lib/ReactElement"`

using the following in my `view` function, using an object to pass in data
```
let view model dispatch =
    R.div [ ]
        [
            ReactElement?createElement( Chart, createObj[ "data" ==> model.Data], [||] ) :?> React.ReactElement<obj>
        ]
```
and then manually editing the js in my createObj to set `data = this.props.data` below
```
let Chart : React.ClassicComponentClass<Datum array> = 
    React.createClass(  createObj [ #manual edit here# ... ] :?> React.ComponentSpec<Datum array,obj> )
```
that was the only way I seemed to be able to pass the state with the approach I was using. AFAIK `this.props.data` doesn't seem to map to `R.Props.Data`

**Comment by aolney** [comment]
The stateless function solved my problem, but I still wonder if the `Classic` version should be removed
```
member React.Globals.createElement : type:#React.ComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ReactElement<'P>, 
member React.Globals.createElement : type:React.ClassicComponentClass<'P> * props:'P * [<ParamArray>] children:React.ReactNode [] -> React.ClassicElement<'P>
```
As it seems the flexible type from [this PR](https://github.com/fable-compiler/Fable/pull/282) made it obsolete and also creates a type inference problem.

**Comment by aolney** [comment]
@Krzysztof-Cieslak Could you comment on the last post? I think this was an unintended side effect from https://github.com/fable-compiler/Fable/pull/282

**Comment by alfonsogarciacaro** [comment]
Sorry for the late, late response but... is this still an issue? :)

**Comment by aolney** [comment]
I'm pretty sure this fixes it :clap: . I will be overhauling all my electron code this fall, so will circle back to confirm. So much has changed with Fable (good things) that I can't check the change against my version .6 code easily.
